#! /usr/bin/env perl
#
# Lingua-Poly   Language Disassembling Library
# Copyright (C) 2018-2019 Guido Flohr <guido.flohr@cantanea.com>
#               All rights reserved
#
# This library is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What the Fuck You Want
# to Public License, Version 2, as published by Sam Hocevar. See
# http://www.wtfpl.net/ for more details.

use  strict;

use Mojo::File 'curfile';
use lib curfile->dirname->sibling('lib')->to_string;

use Bread::Board;

use Lingua::Poly::API::Users::Util qw(empty);

my $basedir = curfile->dirname->dirname;

my $dev = container 'Dev' => as {
};

my $prod = container 'Prod' => as {
};

my $c = container App => ['Env'] => as {
	service WebApp => (
		class => 'Lingua::Poly::API::Users',
		lifecycle => 'Singleton',
		dependencies => {
			database => '/Storage/database',
			configuration => 'Configuration/provider',
			logger => { '/Logging/logger' => { realm => 'core' } },
			userService => '/User/user',
			sessionService => '/User/session',
			requestContextService => 'RequestContext',
			tokenService => 'Token',
			restService => 'REST',
			googleOAuthService => '/OAuth/Google',
			facebookOAuthService => '/OAuth/Facebook',
			emailService => '/Email'
		},
	);

	service RequestContext => (
		class => 'Lingua::Poly::API::Users::Service::RequestContext',
		lifecycle => 'Singleton',
		dependencies => {
			configuration => '/Configuration/provider',
			logger => { '/Logging/logger' => { realm => 'request' }},
		}
	);

	service Token => (
		class => 'Lingua::Poly::API::Users::Service::Token',
		lifecycle => 'Singleton',
		dependencies => {
			configuration => '/Configuration/provider',
			logger => { '/Logging/logger' => { realm => 'request' }},
			database => '/Storage/database',
		}
	);

	service REST => (
		class => 'Lingua::Poly::API::Users::Service::RESTClient',
		lifecycle => 'Singleton'
	);

	service Email => (
		class => 'Lingua::Poly::API::Users::Service::Email',
		dependencies => {
			logger => { '/Logging/logger' => { realm => 'request' }},
		}
	);

	container Storage => as {
		service database => (
			class => 'Lingua::Poly::API::Users::Service::Database',
			lifecycle => 'Singleton',
			dependencies => {
				configuration => '/Configuration/provider',
				logger => { '/Logging/logger' => { realm => 'database' } },
				preparer => 'preparer'
			}
		);
		service preparer => (
			class => 'Lingua::Poly::API::Users::Service::Database::Preparer',
			lifecycle => 'Singleton',
			dependencies => {
				statements => 'statements',
				database => 'database',
				logger => { '/Logging/logger' => { realm => 'database' } },
			},
		);
		service statements =>  (
			class => 'Lingua::Poly::API::Users::Service::Database::Statements',
			lifecycle => 'Singleton',
		)
	};

	# FIXME! This should be a regular service.
	container Configuration => as {
		service config_file => $basedir . '/lingua-poly-service-users.yaml';
		service apiPrefix => '/api/lingua-poly/users/v1';
		service provider => (
			class => 'Lingua::Poly::API::Users::Config',
			lifecycle => 'Singleton',
			dependencies => {
				filename => 'config_file',
				apiPrefix => 'apiPrefix',
			}
		);
	};

	container User => as {
		service user => (
			class => 'Lingua::Poly::API::Users::Service::User',
			lifecycle => 'Singleton',
			dependencies => {
				database  => '/Storage/database',
				logger => { '/Logging/logger' => { realm => 'user' } },
				emailService => '/Email',
			}
		);
		service session => (
			class => 'Lingua::Poly::API::Users::Service::Session',
			lifecycle => 'Singleton',
			dependencies => {
				userService => 'user',
				database  => '/Storage/database',
				logger => { '/Logging/logger' => { realm => 'session' } },
				configuration => '/Configuration/provider',
			}
		);
	};

	container Logging => as {
		service logger => (
			class => 'Lingua::Poly::API::Users::SmartLogger',
			parameters => {
				realm => { isa => 'Str' }
			}
		);
	};

	container OAuth => as {
		service Google => (
			class => 'Lingua::Poly::API::Users::Service::OAuth::Google',
			lifecycle => 'Singleton',
			dependencies => {
				logger => { '/Logging/logger' => { realm => 'session' } },
				configuration => '/Configuration/provider',
				database  => '/Storage/database',
				requestContextService => '/RequestContext',
				sessionService => '/User/session',
				apiPrefix => '/Configuration/apiPrefix',
				restService => '/REST',
				userService => '/User/user',
				emailService => '/Email',
			}
		);
		service Facebook => (
			class => 'Lingua::Poly::API::Users::Service::OAuth::Facebook',
			lifecycle => 'Singleton',
			dependencies => {
				logger => { '/Logging/logger' => { realm => 'session' } },
				configuration => '/Configuration/provider',
				database  => '/Storage/database',
				requestContextService => '/RequestContext',
				sessionService => '/User/session',
				apiPrefix => '/Configuration/apiPrefix',
				restService => '/REST',
				userService => '/User/user',
				emailService => '/Email',
			}
		);
	};
};

# FIXME! Check the value of the --mode option instead!
my $env = $dev;
$ENV{LINGUA_POLY_USERS_DEBUG} = 'all' if !exists $ENV{LINGUA_POLY_USERS_DEBUG};

my $parametrized_component = $c->create(Env => $env);
my $app = $parametrized_component->resolve(service => 'WebApp');
$app->start;
