#! /usr/bin/env perl
#
# Lingua-Poly   Language Disassembling Library
# Copyright (C) 2018-2019 Guido Flohr <guido.flohr@cantanea.com>
#               All rights reserved
#
# This library is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What the Fuck You Want
# to Public License, Version 2, as published by Sam Hocevar. See
# http://www.wtfpl.net/ for more details.

use strict;

use Locale::PO;

my $en_po = '../src/assets/i18n/en-us.po';
my $entries = Locale::PO->load_file_asarray($en_po, 'utf-8')
    or die "$0: cannot open '$en_po' for reading: $!\n";

my @po;
foreach my $entry(@$entries) {
    my $msgid = $entry->dequote($entry->msgid);
    next if '' eq $msgid;
    push @po, Locale::PO->new;
    if ($msgid =~ s/\[\[([_a-zA-Z][_a-zA-Z0-9]*)\]\]/{$1}/g) {
        $po[-1]->add_flag('perl-brace-format');
    }
    $po[-1]->msgid($msgid);
    $po[-1]->msgstr('');
}
my $js_pot = 'js.pot';
Locale::PO->save_file_fromarray($js_pot, \@po, 'utf-8')
    or die "$0: cannot open '$js_pot' for writing: $!\n";
