#! /usr/bin/env perl
#
# Lingua-Poly   Language Disassembling Library
# Copyright (C) 2018 Guido Flohr <guido.flohr@cantanea.com>
#               All rights reserved
#
# This library is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What the Fuck You Want
# to Public License, Version 2, as published by Sam Hocevar. See
# http://www.wtfpl.net/ for more details.

use strict;

use Locale::PO;

my $en_po = '../src/assets/i18n/en.po';
my $entries = Locale::PO->load_file_asarray($en_po, 'utf-8')
    or die "$0: cannot open '$en_po' for reading: $!\n";

my @po;
foreach my $entry(@$entries) {
    my $msgid = $entry->msgid;
    next if '""' eq $msgid;
    my $msgstr = $entry->dequote($entry->msgstr);
    if (!length $msgstr) {
        warn "$en_po: translation missing for $msgid\n";
        next;
    }
    push @po, Locale::PO->new(-msgid => $entry->dequote($msgstr), 
                              -msgstr => '');
}
my $js_pot = 'js.pot';
Locale::PO->save_file_fromarray($js_pot, \@po, 'utf-8')
    or die "$0: cannot open '$js_pot' for writing: $!\n";
